AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'coverage/**/*'
    - 'screenshots/**/*'
    - 'visual_baselines/**/*'
    - 'visual_results/**/*'
    - 'custom/**/*'
    - 'bin/**/*'
    - '*.gemspec'

plugins:
  - rubocop-performance
  - rubocop-rspec

# Documentation requirements for libraries
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Security
Security/Eval:
  Enabled: true

# Complexity metrics - stricter for library code
Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 600
  Exclude:
    - 'lib/appom/configuration.rb' # Configuration class is naturally longer
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'

# Layout and style
Layout/LineLength:
  Max: 160
  AllowedPatterns: 
    - '^\s*#'  # Allow long comments
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Style preferences for library code
Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# Performance optimizations
Performance/RedundantMerge:
  Enabled: true

Performance/StringInclude:
  Enabled: true

# RSpec specific rules
RSpec/ExampleLength:
  Max: 32

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

# Naming conventions
Naming/AccessorMethodName:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: true
  NamePrefix: ['is_', 'has_', 'have_']
  ForbiddenPrefixes: ['is_']
  AllowedMethods: ['is_a?']

# Allow regex literals without %r
Style/RegexpLiteral:
  Enabled: false

# Modern Ruby features
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Error handling
Style/RescueStandardError:
  EnforcedStyle: explicit

# Method definitions
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

# Class and module definitions
Style/ClassAndModuleChildren:
  EnforcedStyle: compact