name: Feature Request
description: Suggest a new feature for Appom
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        Help us understand what you'd like to see in Appom.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a mobile test automation engineer, I want..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternatives have you considered?
      placeholder: Any alternative solutions or features you've considered?
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Code Example
      description: How would you like to use this feature?
      render: ruby
      placeholder: |
        # Example of how the feature would work
        page = MyPage.new
        page.new_awesome_feature
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my project
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
        - label: I'd be willing to help with testing
        - label: I'd be willing to help with documentation